<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDownAccountNumber</name>
   <tag></tag>
   <elementGuidId>e7793dc8-f6d8-4b1d-8006-e8a75495423f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='accountSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accountSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0e319aa-628c-4988-a1a3-8ae2fa45b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-hide</name>
      <type>Main</type>
      <value>noAccount</value>
      <webElementGuid>4d97f1ec-40ad-4456-b857-6c581121a84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>account for account in Accounts</value>
      <webElementGuid>a4cbd9f5-3507-4321-bc55-707c5dc1e49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>1c7af7ed-e006-4422-a24e-a26f78f1953c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountSelect</value>
      <webElementGuid>9808b61a-a054-46c2-9bfc-34843634e42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>a1033ee6-0879-4089-a7e3-08c4b371c390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>selectAcct()</value>
      <webElementGuid>7afe1eef-431b-4cd2-9b89-0086f7dbb574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>e054a5cf-6748-4668-99d1-5b078db0f97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100110021003</value>
      <webElementGuid>27b14711-9a2c-46f8-a902-081460330340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountSelect&quot;)</value>
      <webElementGuid>7eae7e29-b503-4c33-8311-ad7c329d9d60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='accountSelect']</value>
      <webElementGuid>ab39f31c-7f57-4db4-8aca-44ddd8a023d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please open an account with us.'])[1]/following::select[1]</value>
      <webElementGuid>27720ed0-de49-426b-a7fc-81e231a0f117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hermoine Granger'])[1]/following::select[1]</value>
      <webElementGuid>c21c03d6-520d-4d2b-8582-7edb65dfcfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dollar'])[1]/preceding::select[1]</value>
      <webElementGuid>08e3fff4-69ae-486c-b700-1fb4055ee864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6230da6b-7219-464b-a494-554d5d68fd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'accountSelect' and @id = 'accountSelect' and (text() = '100110021003' or . = '100110021003')]</value>
      <webElementGuid>1870d249-14f7-45a1-8a8f-d6e142ecae56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
